# Generated by Django 5.1.6 on 2025-05-20 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambiente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambiente',
            options={'verbose_name': 'Ambiente', 'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='disciplinar',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='data_termino',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='professor',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='capacidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplinar',
            name='carga_horaria',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=5, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Ambiente.ambiente')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ambiente.disciplinar')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Ambiente.professor')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
